### ISSUE TITLE
Not running in iis node 

### ISSUE THREAD

**Issue by pofider** [bjrmatos/electron-html-to#18]
I am not able to make this running in iis node, where the same conversion runs in standalone node. I am running it from jsreport, but I guess that is not the issue. It doesn't work for `dedicated-process` strategy nor the `electron-server`.

It looks to me it is an issue of IPC communication between electron and the main process. The electron.exe is started but there appears to be no communication happening. 

The log from electron server.

```
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:conversion generating new conversion task..
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:conversion conversion task id: 8d4e9cd8-4cad-4b30-9168-7c242bd12c03
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:conversion creating temporal html files in C:\jsreport\playground-test\temp..
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:conversion creating temporal html file [type: html] in C:\jsreport\playground-test\temp\8d4e9cd8-4cad-4b30-9168-7c242bd12c03html.html..
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:conversion starting conversion task [strategy:electron-server][task id:8d4e9cd8-4cad-4b30-9168-7c242bd12c03] with options: { browserWindow: { width: 10, height: 10, webPreferences: { javascript: true } },
  waitForJSVarName: 'JSREPORT_READY_TO_START',
  delay: undefined,
  waitForJS: false,
  converterPath: 'C:\\jsreport\\playground-test\\node_modules\\electron-html-to\\lib\\converters\\pdf.js',
  pdf: 
   { marginsType: 0,
     pageSize: 'A4',
     printBackground: true,
     landscape: false },
  htmlFile: 'C:\\jsreport\\playground-test\\temp\\8d4e9cd8-4cad-4b30-9168-7c242bd12c03html.html',
  url: 'file:///electron-html-to/C%3A%5Cjsreport%5Cplayground-test%5Ctemp%5C8d4e9cd8-4cad-4b30-9168-7c242bd12c03html.html',
  chromeCommandLineSwitches: { 'ignore-certificate-errors': null },
  extraHeaders: {},
  output: 
   { tmpDir: 'C:\\jsreport\\playground-test\\temp',
     id: '8d4e9cd8-4cad-4b30-9168-7c242bd12c03' } }
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:electron-server-strategy checking if electron workers have started..
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:electron-server-strategy starting electron workers..
Sun, 13 Dec 2015 13:10:51 GMT electron-workers:manager starting 1 worker(s)..
Sun, 13 Dec 2015 13:10:51 GMT electron-workers:manager creating worker 1 with options: { debug: undefined,
  debugBrk: undefined,
  env: 
   { chromeCommandLineSwitches: '{"ignore-certificate-errors":null}',
     allowLocalFilesAccess: 'false' },
  stdio: [ null, null, null, 'ipc' ],
  killSignal: 'SIGKILL',
  electronArgs: [],
  pathToElectron: 'C:\\jsreport\\playground-test\\node_modules\\electron-prebuilt\\dist\\electron.exe',
  pathToScript: 'C:\\jsreport\\playground-test\\node_modules\\electron-html-to\\lib\\scripts\\serverScript.js',
  hostEnvVarName: 'ELECTRON_WORKER_HOST',
  portEnvVarName: 'ELECTRON_WORKER_PORT',
  host: '127.0.0.1',
  portLeftBoundary: undefined,
  portRightBoundary: undefined }
Sun, 13 Dec 2015 13:10:51 GMT electron-workers:worker starting worker [eef3aa90-a19a-11e5-a58e-43f11f925516]..
Sun, 13 Dec 2015 13:10:51 GMT electron-workers:worker trying to find free port..
Sun, 13 Dec 2015 13:10:51 GMT electron-workers:worker spawning process for worker [eef3aa90-a19a-11e5-a58e-43f11f925516] with args: [ 'C:\\jsreport\\playground-test\\node_modules\\electron-html-to\\lib\\scripts\\serverScript.js' ] and options: { env: 
   { chromeCommandLineSwitches: '{"ignore-certificate-errors":null}',
     allowLocalFilesAccess: 'false',
     ELECTRON_WORKER_HOST: '127.0.0.1',
     ELECTRON_WORKER_PORT: 51403,
     ELECTRON_WORKER_ID: 'eef3aa90-a19a-11e5-a58e-43f11f925516' },
  stdio: [ null, null, null, 'ipc' ] }
Sun, 13 Dec 2015 13:10:51 GMT electron-html-to:electron-server-strategy establishing listeners for electron logs in worker [eef3aa90-a19a-11e5-a58e-43f11f925516]..
Sun, 13 Dec 2015 13:10:51 GMT electron-workers:worker checking if worker [eef3aa90-a19a-11e5-a58e-43f11f925516] is alive..
Sun, 13 Dec 2015 13:10:59 GMT electron-workers:worker worker [eef3aa90-a19a-11e5-a58e-43f11f925516] is not alive..
Sun, 13 Dec 2015 13:10:59 GMT electron-workers:manager electron manager could not start all workers..
Sun, 13 Dec 2015 13:10:59 GMT electron-html-to:electron-server-strategy electron workers could not start..
Sun, 13 Dec 2015 13:10:59 GMT electron-html-to:electron-server-strategy conversion ended with error..
2015-12-13T13:10:59.742Z - [31merror[39m: Error when processing render request Error during rendering report: electron manager could not start all workers.. Error: electron manager could not start all workers..
    at startHandler (C:\jsreport\playground-test\node_modules\electron-workers\lib\ElectronManager.js:128:37)
    at C:\jsreport\playground-test\node_modules\electron-workers\lib\ElectronWorker.js:191:18
    at C:\jsreport\playground-test\node_modules\electron-workers\lib\ElectronWorker.js:215:16
    at Socket.<anonymous> (C:\jsreport\playground-test\node_modules\electron-workers\lib\checkPortStatus.js:49:5)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
From previous event:
    at Object.electron-pdf (C:\jsreport\playground-test\node_modules\jsreport-core\lib\reporter.js:147:40)
    at C:\jsreport\playground-test\node_modules\toner\lib\toner.js:124:47
    at C:\jsreport\playground-test\node_modules\toner\lib\toner.js:82:17
    at C:\jsreport\playground-test\node_modules\toner\lib\listeners.js:38:17
    at C:\jsreport\playground-test\node_modules\jsreport-core\lib\reporter.js:121:7
```

For `dedicated-process` strategy it also spawns electron.exe and then get stucks

```
Sun, 13 Dec 2015 13:20:27 GMT electron-html-to:dedicated-process-strategy electron executable path returned from electron-prebuilt module: C:\jsreport\playground-test\node_modules\electron-prebuilt\dist\electron.exe
Sun, 13 Dec 2015 13:20:27 GMT electron-html-to:dedicated-process-strategy spawing new electron process..
Sun, 13 Dec 2015 13:20:27 GMT electron-html-to:dedicated-process-strategy processing conversion..
```

node 4.2.3
electron-prebuilt 0.35.4

**Comment by bjrmatos** [comment]
seems like iisnode doesn't handle IPC connections nicely.. let me check on a windows machine with iisnode installed

**Comment by bjrmatos** [comment]
i found another bug in my windows machine.. at least in windows 7 the electron process hangs for not getting the focus in the current window.

testing with the flag `ELECTRON_HTML_TO_DEBUGGING=true` enables show the electron window..

**Comment by bjrmatos** [comment]
are you using azure with iisnode?

**Comment by pofider** [comment]
`ELECTRON_HTML_TO_DEBUGGING=true` works nicely on my local windows 10 as well on azure (without iisnode) windows server 2012. The electron window seems to pop up after the rendering. With iisnode it doesn't get opened.

I have the iisnode on custom Azure VM with windows server.

**Comment by pofider** [comment]
I can mail you the login if you want...

**Comment by bjrmatos** [comment]
sure, i know how to fix that problem. let me test in my local iisnode, if it works then i will test on your azure account

**Comment by bjrmatos** [comment]
but let's wait.. maybe with my patch there is no need to test on your account

**Comment by bjrmatos** [comment]
quick question: how are you setting env vars in iisnode? just wanna mention that issnode has a special way to propagate env vars

**Comment by pofider** [comment]
Through web.config appSettings

``` xml
<configuration>
  <appSettings>
    <add key="DEBUG" value="*" />
    <add key="ELECTRON_HTML_TO_DEBUGGING=true" value="true" />
  </appSettings>
```

**Comment by bjrmatos** [comment]
after debugging multiple times and in different ways i have discovered that electron hangs (only in iisnode) in [this part](https://github.com/bjrmatos/electron-html-to/blob/master/src/scripts/registerProtocol.js#L44).. don't know why but i will dive into it

**Comment by bjrmatos** [comment]
in other words the `readFile` operation never ends

**Comment by bjrmatos** [comment]
using `fs.readFileSync` works! (don't know why.. maybe iisnode patch the `fs` module?).

one more problem to solve on iisnode.. since electron doesn't give me the number of pages of the PDF, i was forced to use a pdf parser from mozila's pdf.js, the parser is great but is based completly in the web.. i have noticed before that some parts of the parser hangs when running on node.js, i was able to fix that with a hack but now i have discovered that it hangs on iisnode

**Comment by pofider** [comment]
You made it, cool! I will try it myself.

I use the number of pages information only to charge credits in jsreportonline. But it is not something we need to have I guess.

**Comment by bjrmatos** [comment]
i will try to make it work.. I do not like to refuse a challenge :smiley: 

however i have already asked support in electron for that feature (including header and footer generation in the PDF)

debugging this problem let me discover some minor bugs.. i will push a fix later so we can try again with a new version

**Comment by bjrmatos** [comment]
@pofider can you try on latest version?

**Comment by pofider** [comment]
Unfortunately I observe the same problem - electron executable hangs.

**Comment by bjrmatos** [comment]
it doesn't work in local o azure? or both? i have tested it locally

**Comment by pofider** [comment]
Azure VM - I will mail you credentials

**Comment by bjrmatos** [comment]
closing until plain iisnode + electron works -> https://github.com/bjrmatos/iisnode-electron-spawn-bug
