### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by Ctucker9233** [bjrmatos/electron-html-to#459]
I get this timeout error when I use electron-to-html to convert an html file to pdf.

{ Error: Worker Timeout, the worker process does not respond after 10000 ms
    at Timeout._onTimeout (C:\Users\Owner\Desktop\code\PDF-Profile-Generator\node_modules\electron-workers\lib\ElectronManager.js:377:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  workerTimeout: true,
  message:
   'Worker Timeout, the worker process does not respond after 10000 ms',
  electronTimeout: true }

Here's the js call:
var convertFactory = require('electron-html-to');

            var conversion = convertFactory({
                converterPath: convertFactory.converters.PDF
            });

            conversion({ file: './profile.html' }, function (err, result) {
                if (err) {
                    return console.error(err);
                }

                console.log(result.numberOfPages);
                console.log(result.logs);
                result.stream.pipe(fs.createWriteStream(__dirname + '/profile.pdf'));
                conversion.kill();
Any assistance with an extra parameters I need to use would be helpful.

**Comment by StephanieZ** [comment]
@Ctucker9233 I had to back down to an earlier version of electron and electron-html-to to get this to work properly again. I went back to "electron": "^5.0.12", "electron-html-to": "^2.6.0". In case you need a workaround in the meantime.

**Comment by bjrmatos** [comment]
@StephanieZ yes, i think new versions of electron have a bit of different api for startup, so it probably breaks some internal calls.. i will try to check the support for these new versions (should be 6.x.x, 7.x.x), as always PR welcome if someone can find some time before i can get to this.

@Ctucker9233 just to confirm, i guess you are using a version of electron > 5.x.x, right?

**Comment by Ctucker9233** [comment]
@bjrmatos Most likely. I simply did npm install and I'm sure it grabbed the newest version.
